name: Supabase Preview Branch

on:
  pull_request:
    branches:
      - main
      - versiontest
      - versionTest
    types: [opened, reopened, synchronize]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      PROJECT_ID: zemglmsosdrdkenazqrw

    steps:
      - uses: actions/checkout@v3

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Create Preview Branch
        run: |
          supabase link --project-ref $PROJECT_ID
          supabase db push 